# Generated by Django 4.0.4 on 2022-04-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
