# Generated by Django 4.0.4 on 2022-04-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QES', '0002_profile_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
