# Generated by Django 4.0.4 on 2022-04-21 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QES', '0006_remove_questions_upvotes_questions_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
