# Generated by Django 4.0.4 on 2022-04-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QES', '0009_alter_answers_ans_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.CharField(choices=[('CSE/ISE', 'CSE/ISE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('AI/ML', 'AI/ML'), ('AERO', 'AERO')], default='CSE/ISE', max_length=255),
        ),
    ]
