# Generated by Django 4.0.4 on 2022-04-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QES', '0010_alter_questions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='quest_image',
            field=models.ImageField(default='test.png', upload_to='question_pics'),
        ),
    ]
