# Generated by Django 4.0.4 on 2022-04-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QES', '0011_questions_quest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='downvoted',
            field=models.CharField(default='False', max_length=6),
        ),
        migrations.AddField(
            model_name='questions',
            name='totalvotes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
