# Generated by Django 4.0.4 on 2022-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QES', '0012_questions_downvoted_questions_totalvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='downvoted',
            field=models.CharField(default='False', max_length=6),
        ),
        migrations.AddField(
            model_name='answers',
            name='totalvotes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
