# Generated by Django 4.0.4 on 2022-04-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QES', '0013_answers_downvoted_answers_totalvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quest_image',
            field=models.ImageField(null=True, upload_to='question_pics'),
        ),
    ]
