# Generated by Django 4.0.4 on 2022-04-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QES', '0014_alter_questions_quest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='quest_image',
        ),
    ]
